simplemooc/courses/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<slug>[\w_-]+)/$', views.details, name='details'),
    url(
        r'^(?P<slug>[\w_-]+)/inscricao/$',
        views.enrollment,
        name='enrollment'
    ),
    url(
        r'^(?P<slug>[\w_-]+)/cancelar-inscricao/$',
        views.undo_enrollment,
        name='undo_enrollment'
    ),
    url(
        r'^(?P<slug>[\w_-]+)/anuncios/$',
        views.announcements,
        name='announcements'
    ),
    url(
        r'^(?P<slug>[\w_-]+)/anuncio/(?P<pk>\d+)/$',
        views.show_announcement,
        name='show_announcement'
    ),
    url(
        r'^(?P<slug>[\w_-]+)/aulas/$',
        views.lessons,
        name='lessons'
    ),
    url(
        r'^(?P<slug>[\w_-]+)/aulas/(?P<pk>\d+)/$',
        views.lesson,
        name='lesson'
    ),
    url(
        r'^(?P<slug>[\w_-]+)/materiais/(?P<pk>\d+)/$',
        views.material,
        name='material'
    ),
]

simplemooc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^', include('simplemooc.core.urls', namespace='core')),
    url(r'^conta/', include('simplemooc.accounts.urls', namespace='accounts')),
    url(r'^cursos/', include('simplemooc.courses.urls', namespace='courses')),
    url(r'^forum/', include('simplemooc.forum.urls', namespace='forum')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

simplemooc/courses/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from simplemooc.core.mail import send_mail_template


class CourseManager(models.Manager):

    def search(self, query):
        return self.get_queryset().filter(
            models.Q(name__icontains=query) |
            models.Q(description__icontains=query)
        )


class Course(models.Model):

    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Atalho')
    description = models.TextField('Descrição Simples', blank=True)
    about = models.TextField('Sobre o Curso', blank=True)
    start_date = models.DateField(
        'Data de Início', null=True, blank=True
    )
    image = models.ImageField(
        upload_to='courses/images',
        verbose_name='Imagem',
        null=True,
        blank=True,
    )
    created_at = models.DateTimeField(
        'Criado em ', auto_now_add=True
    )
    updated_at = models.DateTimeField(
        'Atualizado em ', auto_now=True
    )

    objects = CourseManager()

    def __str__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return('courses:details', (), {'slug': self.slug})

    def release_lessons(self):
        today = timezone.now().date()
        print('Entrou ')
        print(today)
        return self.lessons.filter(release_date__lte=today)

    class Meta:
        verbose_name = 'Curso'
        verbose_name_plural = 'Cursos'
        ordering = ['name']


class Lesson(models.Model):
    name = models.CharField('Nome', max_length=100)
    description = models.TextField('Descrição', blank=True)
    number = models.IntegerField('Número (ordem', blank=True, default=0)
    release_date = models.DateField('Data de Liberação', blank=True, null=True)
    course = models.ForeignKey(
        Course,
        verbose_name='Curso',
        related_name='lessons'
    )
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    uptdate_at = models.DateTimeField('Atualizado em', auto_now=True)

    def is_available(self):
        if self.release_date:
            today = timezone.now().date()
            return self.release_date >= today
        return False

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Aula'
        verbose_name_plural = 'Aulas'
        ordering = ['number']


class Material(models.Model):
    name = models.CharField('Nome', max_length=100)
    embedded = models.TextField('Vídeo embedded', blank=True)
    file = models.FileField(
        upload_to='lessions/materials',
        blank=True,
        null=True
    )

    lesson = models.ForeignKey(
        Lesson,
        verbose_name='Aula',
        related_name='materials')

    def is_embedded(self):
        return bool(self.embedded)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Material'
        verbose_name_plural = 'Materiais'


class Enrollment(models.Model):

    STATUS_CHOICES = (
        (0, 'Pendente'),
        (1, 'Aprovado'),
        (2, 'Cancelado'),
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name='Usuário',
        related_name='enrollments'
        )
    course = models.ForeignKey(
        Course,
        verbose_name='Curso',
        related_name='enrollments'
        )
    status = models.IntegerField(
        'Situação',
        choices=STATUS_CHOICES,
        default=1,
        blank=True
    )
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)

    def acitve(self):
        self.status = 1
        self.save()

    def deacitve(self):
        self.status = 2
        self.save()

    def is_approved(self):
        return self.status == 1

    class Meta:
        verbose_name = 'Inscrição'
        verbose_name_plural = 'Inscrições'
        unique_together = (('user', 'course'))


class Announcement(models.Model):

    course = models.ForeignKey(
        Course,
        verbose_name='Curso',
        related_name='announcements'
    )
    title = models.CharField('Título', max_length=100)
    content = models.TextField('Conteúdo')

    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    uptdate_at = models.DateTimeField('Atualizado em', auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Anúcio'
        verbose_name_plural = 'Anúncios'
        ordering = ['-created_at']


class Comment(models.Model):
    announcement = models.ForeignKey(
        Announcement,
        verbose_name='Anúncio',
        related_name='comments'
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name='Usuário'
    )
    comment = models.TextField('Comentário')
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    uptdate_at = models.DateTimeField('Atualizado em', auto_now=True)

    class Meta:
        verbose_name = 'Comentário'
        verbose_name_plural = 'Comentários'
        ordering = ['created_at']


def post_save_announcement(instance, created, **kwargs):
    if created:
        subject = instance.title
        template_name = 'courses/announcement_mail.html'
        context = {
           'announcement': instance
        }
        enrrolments = Enrollment.objects.filter(
            course=instance.course,
            status=1
        )
        for enrrolment in enrrolments:
            recipient_list = [enrrolment.user.email]
            send_mail_template(
                subject,
                template_name,
                context,
                recipient_list
            )

models.signals.post_save.connect(
    post_save_announcement,
    sender=Announcement,
    dispatch_uid='post_save_announcement'
)

simplemooc/courses/forms.py
from django import forms
# from django.core.mail import send_mail
from django.conf import settings
from simplemooc.core.mail import send_mail_template
from .models import Comment


class ContactCourse(forms.Form):

    name = forms.CharField(label='Nome', max_length=100)
    email = forms.EmailField(label='E-mail')
    message = forms.CharField(
        label='Mensagem/Dúvida', widget=forms.Textarea
    )

    def send_mail(self, course):
        subject = '[%s] Contato' % course
        context = {
            'name': self.cleaned_data['name'],
            'email': self.cleaned_data['email'],
            'message': self.cleaned_data['message'],
        }

        template_name = 'courses/contact_email.html'
        send_mail_template(
            subject,
            template_name,
            context,
            [settings.CONTACT_EMAIL]
        )

#        message = message % context

#       #send_mail(
#       #    subject,
#            message,
#            settings.DEFAULT_FROM_EMAIL,
#            [settings.CONTACT_EMAIL]
#        )


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['comment']

simplemooc/courses/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import Course, Enrollment, Lesson, Material
from .forms import ContactCourse, CommentForm
from .decorators import enrollment_required


# Create your views here.
def index(request):

    # Lista de cursos
    courses = Course.objects.all()
    # Criação do contexto para enviar para o template
    context = {
        'courses': courses
    }

    template_name = 'courses/index.html'
    return render(request, template_name, context)

# def details(request,pk):
#    course = get_object_or_404(Course,pk=pk)
#    context = {
#        'course' : course
#    }
#    template_name = 'courses/details.html'
#    return render(request, template_name, context )


def details(request, slug):
    course = get_object_or_404(Course, slug=slug)
    context = {}

    if request.method == 'POST':
        form = ContactCourse(request.POST)
        if form.is_valid():
            context['is_valid'] = True
            form.send_mail(course)
            form = ContactCourse()
    else:
        form = ContactCourse()

    context['form'] = form
    context['course'] = course

    template_name = 'courses/details.html'
    return render(request, template_name, context)


@login_required
def enrollment(request, slug):
    course = get_object_or_404(Course, slug=slug)
    enrollment, created = Enrollment.objects.get_or_create(
        user=request.user, course=course
    )
    if created:
        # enrrolment.active()
        messages.success(request, 'Você foi inscrito no curso com sucesso')
    else:
        messages.info(request, 'Você já está inscrito neste curso')
    return redirect('accounts:dashboard')


@login_required
def undo_enrollment(request, slug):
    course = get_object_or_404(Course, slug=slug)
    enrollment = get_object_or_404(
            Enrollment,
            user=request.user,
            course=course
        )
    if request.method == 'POST':
        enrollment.delete()
        messages.success(request, 'Sua inscrição foi cancelada com sucesso')
        return redirect('accounts:dashboard')

    template_name = 'courses/undo_enrollment.html'
    context = {
        'enrollment': enrollment,
        'course': course
    }
    return render(request, template_name, context)


@login_required
@enrollment_required
def announcements(request, slug):
    course = request.course

    template_name = 'courses/announcements.html'
    context = {
        'course': course,
        'announcements': course.announcements.all()
    }
    return render(request, template_name, context)


@login_required
@enrollment_required
def show_announcement(request, slug, pk):
    course = request.course

    announcement = get_object_or_404(course.announcements.all(), pk=pk)

    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.user = request.user
        comment.announcement = announcement
        comment.save()
        form = CommentForm()
        messages.success(request, 'Seu comentário foi enviado com sucesso.')

    template_name = 'courses/show_announcement.html'
    context = {
        'course': course,
        'announcement': announcement,
        'form': form
    }
    return render(request, template_name, context)


@login_required
@enrollment_required
def lessons(request, slug):
    course = request.course
    template_name = 'courses/lessons.html'
    lessons = course.release_lessons()
    if request.user.is_staff:
        lessons = course.lessons.all()
    context = {
        'course': course,
        'lessons': lessons
    }
    return render(request, template_name, context)


@login_required
@enrollment_required
def lesson(request, slug, pk):
    course = request.course
    print("****************************************")
    print(course)
    print(slug)
    print(pk)
    print("****************************************")
    lesson = get_object_or_404(Lesson, pk=pk, course=course)
    if not request.user.is_staff and not lesson.is_available():
        messages.error(request, 'Esta aula não está disponível')
        return redirect('courses:lessons', slug=course.slug)
    template_name = 'courses/lesson.html'
    context = {
        'course': course,
        'lesson': lesson
    }
    return render(request, template_name, context)


@login_required
@enrollment_required
def material(request, slug, pk):
    course = request.course
    material = get_object_or_404(Material, pk=pk, lesson__course=course)
    lesson = material.lesson
    if not request.user.is_staff and not lesson.is_available():
        messages.error(request, 'Esta material não pode ser baixado!')
        return redirect('couses:lesson', slug.course.slug, pk=lesson.pk)
    if not material.is_embedded():
        return redirect(material.file.url)
    template_name = 'courses/material.html'
    context = {
        'course': course,
        'lesson': lesson,
        'material': material,
    }
    return render(request, template_name, context)

simplemooc/courses/templates/courses/announcement_mail.html
{{ announcement.content|linebreaks }}

simplemooc/courses/templates/courses/announcements.html
{% extends "courses/course_dashboard.html" %}

{% block dashboard_content %}
<div class="well">
    {% for announcement in announcements  %}
    <h2>
        <a href="{% url 'courses:show_announcement' course.slug announcement.pk %}">
        {{ announcement.title }}
        </a>
    </h2>
    {{ announcement.content|linebreaks }}
    <p>
        <a href="{% url 'courses:show_announcement' course.slug announcement.pk %}#comments" title="">
        <i class="fa fa-comments-o"></i>
        {% with comments_count=announcement.comments.count %}
        {{ comments_count }} 
        Comentário{{ comments_count|pluralize }}
        {% endwith %}
        </a>
    </p>
    {% empty %}
        <h2>Nenhum anúncio criado.</h2>
    {% endfor %}
</div>
{% endblock %}

simplemooc/courses/templates/courses/contact_email.html
<p><strong>Nome:</strong>{{ name }}</p>
<p><strong>Email:</strong>{{ email }}</p>
{{ message|linebreaks }}

simplemooc/courses/templates/courses/course_dashboard.html
{% extends "accounts/dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li></li>
    <li><a href="{% url 'courses:announcements' course.slug %}">{{ course }}</a></li>
{% endblock breadcrumb %}

{% block menu_options %}
<li class="pure-menu-heading">
    {{ course }}
</li>
<li>
    <a href="{% url 'courses:lessons' course.slug %}">
        <i class="fa fa-video-camera"></i>
        Aulas e Materiais
    </a>
</li>
<li>
    <a href="#">
        <i class="fa fa-info-circle"></i>
        Informações
    </a>
</li>
<li>
    <a href="{% url 'courses:announcements' course.slug %}">
        <i class="fa fa-envelope"></i>
        Anúncios
    </a>
</li>
<li>
    <a href="#">
        <i class="fa fa-comments"></i>
        Fórum de Dúvidas
    </a>
</li>
{{ block.super }}
{% endblock %}

simplemooc/courses/templates/courses/details.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="splash">
    <div class="pure-g-r">
        <div class="pure-u-1">
            <div class="l-box splash-text">
                <h1 class="splash-head">
                    {{ course }}
                </h1>
                <h2 class="splash-subhead">
                    {{ course.description }}
                </h2>
                <p>
                    <a href="{% url 'courses:enrollment' course.slug %}" class="pure-button primary-button">Inscreva-se</a>
                </p>
            </div>
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Sobre o Curso</h4>
            {{ course.about|linebreaks }}
        </div>
    </div>
    <div class="pure-u-1-3">
        <div class="l-box">
            {% if course.image %}
            <img src="{{ course.image.url }}" alt="" />
            {% else %}
            <img src="{% static 'img/course-image.png' %}" alt="" />
            {% endif %}
        </div>
        <h4>Dúvidas?</h4>
        <p>
            <a href="#contato" title="" class="pure-button">Fale Conosco</a>
        </p>
    </div>
</div>
<div class="pure-g-r content-ribbon" id="contato">
    <div class="pure-u-1">
        <h3>Tire sua dúvida sobre o Curso</h3>
        {% if is_valid %}
        <p>Você enviou o formulário com sucesso</p>
        {% endif %}
        <form action="#contato" class="pure-form pure-form-aligned" method="post">
            {% csrf_token %}
            <fieldset>
                {% for field in form %}
                <div class="pure-controls">
                    {{ field.label_tag }}
                    {{ field }}
                    {% if field.errors %}
                    <ul class="errorlist">
                        {% for error in field.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>
                {% endfor %}
                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                </div>
            </fieldset>
        </form>
    </div>
</div>

{% endblock %}

simplemooc/courses/templates/courses/index.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <div class="l-box">
            <h4 class="content-subhead">Listagem de Cursos do SimpleMOOC</h4>
            <p>Abaixo a lista de cursos disponíveis na plataforma</p>
        </div>
    </div>
</div>
{% for course in courses %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1-3">
        <div class="l-box">
            <a href="{{ course.get_absolute_url }}">
            {% if course.image %}
            <img src="{{ course.image.url }}" alt="{{ course.name }}" />
            {% else %}
            <img src="{% static 'img/course-image.png' %}" alt="{{ course.name }}" />
            {% endif %}
            </a>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead"><a href="{{ course.get_absolute_url }}" title="">{{ course.name }}</a></h4>
            {{ course.description|linebreaks }}
        </div>
    </div>
</div>
{% empty %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <div class="l-box">
            <p>Nenhum curso está disponível na plataforma</p>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

simplemooc/courses/templates/courses/lesson.html
{% extends "courses/course_dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li></li>
    <li><a href="{% url 'courses:announcements' course.slug %}">{{ course }}</a></li>
    <li><a href="{% url 'courses:lesson' course.slug lesson.pk %}">{{ lesson }}</a></li>
{% endblock breadcrumb %}

{% block dashboard_content %}
<div class="well">
    <h2><a href="{% url 'courses:lesson' course.slug lesson.pk %}">{{ lesson }}</a></h2>
    {{ lesson.description|linebreaks}}
    <p>
        <h4>Material da Aula</h4>
        <table class="pure-table full">
            <thead>
                <tr>
                    <th>
                        Nome
                    </th>
                    <th>
                        Ação
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for material in lesson.materials.all %}
                <tr class="{% cycle '' 'pure-table-odd' %}">
                    <td>
                        {{ material }}
                    </td>
                    <td>
                        {% if material.is_embedded %}
                        <a href="{% url 'courses:material' course.slug material.pk %}">
                            <i class"fa fa-video-camera"></i>
                            Acessar
                        </a>
                        {% else %}
                        <a _target="_blank" href="{{ material.file.url }}">
                            <i class"fa fa-video-camera"></i>
                            Baixar
                        </a>
                        {% endif %}
                    </td>
                </tr>
                   
                {% endfor %}
            </tbody>
        </table>
    </p>
</div>

{% endblock dashboard_content %}

simplemooc/courses/templates/courses/lessons.html
{% extends "courses/course_dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li></li>
    <li><a href="{% url 'courses:lessons' course.slug %}">Aulas</a></li>
{% endblock breadcrumb %}

{% block dashboard_content %}
{% for lesson in lessons %}
<div class="well">
    <h2><a href="{% url 'courses:lesson' course.slug lesson.pk %}">{{ lesson }}</a></h2>
    <p>
        {{ lesson.description|truncatewords:'20' }}
        <br />
        <a href="{% url 'courses:lesson' course.slug lesson.pk %}" title="">
        <i class="fa fa-eye"></i>
        Acessar Aula
        </a>
    </p>
</div>
{% empty %}	
<div class="well">
	<h2>
		Nenhuma aula disponível.
	</h2>
</div>
{% endfor %}
{% endblock dashboard_content %}

simplemooc/courses/templates/courses/material.html
{% extends "courses/course_dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li></li>
    <li><a href="{% url 'courses:announcements' course.slug %}">{{ course }}</a></li>
    <li><a href="{% url 'courses:lesson' course.slug lesson.pk %}">{{ lesson }}</a></li>
    <li><a href="{% url 'courses:material' course.slug material.pk %}">{{ material }}</a></li>
{% endblock breadcrumb %}

{% block dashboard_content %}
<div class="well">
	<h2><a href="{% url 'courses:material' course.slug material.pk %}">{{ material }}</a></h2>
	{{ material.embedded|safe }}
	<p><a href="{% url 'courses:lesson' course.slug lesson.pk %}">Voltar</a></p>
</div>
{% endblock dashboard_content %}

simplemooc/courses/templates/courses/show_announcement.html
{% extends "courses/course_dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li></li>
    <li><a href="{% url 'courses:show_announcements' course.slug announcement.pk %}">{{ announcement }}</a></li>
{% endblock breadcrumb %}


{% block dashboard_content %}
<div class="well">
    <h2>{{ announcement.title }}</h2>
    {{ announcement.content|linebreaks }}
</div>
<div class="well">
    <h4 id="comments">Comentários
    <a class="fright" href="#add_comment">Comentar</a></h4>
    <hr />
    {% for comment in announcement.comments.all %}
    <p>
        <strong>{{ comment.user }}</strong> disse à {{ comment.created_at|timesince }} dias atrás: <br />
        {{ comment.comment|linebreaksbr}}
    </p>
    <hr />
    {%empty %}
    <p>
        Nenhum comentário para este anúncio
    </p>
    {% endfor %}
    <form method="post" class="pure-form pure-form-stacked" id="add_comment">
        {% csrf_token %}
        <fieldset>
            {{ form.non_field_errors }}
            {% for field in form %}
            <div class="pure-control-group">
                {{ field.label_tag }}
                {{ field }}
                {{ field.errors }}
            </div>
            {% endfor %}
            <div class="pure-controls">
                <button type="submit" class="pure-button pure-button-primary">Enviar</button>
            </div>
        </fieldset>
    </form>
</div>
{% endblock %}

simplemooc/courses/templates/courses/undo_enrollment.html
{% extends "courses/course_dashboard.html" %}

{% block dashboard_content %}
	<form action="" method="POST">
		{% csrf_token %}
		<h3>Você deseja realmente cancelar a inscrição deste curso?</h3>
		<div class="pure-controls">
			<button type="submit" class="pure-button pure-button-primary">Confirmar</button>
			<a href="{% url 'courses:undo_enrollment' course.slug %}" class="pure-button">Voltar</a>
		</div>
	</form>

{% endblock %}