simplemooc/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from . import views

urlpatterns = [
      url(r'^$', views.dashboard, name='dashboard'),
      url(
          r'^entrar/$',
          login,
          {'template_name': 'accounts/login.html'},
          name='login'
      ),
      url(r'^sair/$', logout, {'next_page': 'core:home'}, name='logout'),
      url(r'^cadastre-se/$', views.register, name='register'),
      url(
        r'^nova-senha/$',
        views.password_reset,
        name='password_reset'
      ),
      url(
        r'^confirmar-nova-senha/(?P<key>\w+)/$',
        views.password_reset_confirm,
        name='password_reset_confirm'
        ),
      url(r'^editar/$', views.edit, name='edit'),
      url(r'^editar-senha/$', views.edit_password, name='edit-password')]

simplemooc/courses/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<slug>[\w_-]+)/$', views.details, name='details'),
    url(
        r'^(?P<slug>[\w_-]+)/inscricao/$',
        views.enrollment,
        name='enrollment'
    ),
    url(
        r'^(?P<slug>[\w_-]+)/cancelar-inscricao/$',
        views.undo_enrollment,
        name='undo_enrollment'
    ),
    url(
        r'^(?P<slug>[\w_-]+)/anuncios/$',
        views.announcements,
        name='announcements'
    ),
    url(
        r'^(?P<slug>[\w_-]+)/anuncio/(?P<pk>\d+)/$',
        views.show_announcement,
        name='show_announcement'
    ),
    url(
        r'^(?P<slug>[\w_-]+)/aulas/$',
        views.lessons,
        name='lessons'
    ),
    url(
        r'^(?P<slug>[\w_-]+)/aulas/(?P<pk>\d+)/$',
        views.lesson,
        name='lesson'
    ),
    url(
        r'^(?P<slug>[\w_-]+)/materiais/(?P<pk>\d+)/$',
        views.material,
        name='material'
    ),
]

simplemooc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^', include('simplemooc.core.urls', namespace='core')),
    url(r'^conta/', include('simplemooc.accounts.urls', namespace='accounts')),
    url(r'^cursos/', include('simplemooc.courses.urls', namespace='courses')),
    url(r'^forum/', include('simplemooc.forum.urls', namespace='forum')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

simplemooc/accounts/models.py
import re

from django.db import models
from django.core import validators
from django.contrib.auth.models import (AbstractBaseUser,
    PermissionsMixin, UserManager)
from django.conf import settings


class User(AbstractBaseUser, PermissionsMixin):

    username = models.CharField(
        'Nome de Usuário',
        max_length=30,
        unique=True,
        validators=[validators.RegexValidator(
            re.compile('^[\w.@+-]+$'),
            'O nome do usuário só pode conter letras, dígitos ou @/./+/-/_',
            'invalid'
        )]
    )
    email = models.EmailField('E-mal', unique=True)
    name = models.CharField('Nome', max_length=100, blank=True)
    is_active = models.BooleanField('Está ativo?', blank=True, default=True)
    is_staff = models.BooleanField('É da equipe?', blank=True, default=True)
    date_joined = models.DateTimeField(
        'Data de Entrada', auto_now_add=True
    )

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.name or self.username

    def get_short_name(self):
        return self.username

    def get_full_name(self):
        return str(self)

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'


class PasswordReset(models.Model):

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name='Usuários',
        related_name='resets'
        )
    key = models.CharField('Chave', max_length=100, unique=True)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    confirmed = models.BooleanField('Confirmado?', default=False, blank=True)

    def __str__(self):
        return '{0} em {1}'.format(self.user, self.created_at)

    class Meta:
        verbose_name = 'Nova Senha'
        verbose_name_plural = 'Novas Senhas'
        ordering = ['-created_at']

simplemooc/accounts/forms.py
from django import forms
# from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

from simplemooc.core.mail import send_mail_template
from simplemooc.core.utils import generate_hash_key

from .models import PasswordReset

User = get_user_model()


class PasswordResetForm(forms.Form):

    email = forms.EmailField(label='E-mail')

    def clean_email(self):
        email = self.cleaned_data['email']

        if User.objects.filter(email=email).exists():
            return email
        raise forms.ValidationError(
            'Nenhum usuário encontrado com este email')

    def save(self):
        user = User.objects.get(email=self.cleaned_data['email'])
        key = generate_hash_key(user.email)
        reset = PasswordReset(key=key, user=user)
        reset.save()
        template_name = 'accounts/password_reset_mail.html'
        subject = 'Criar nova senha'
        context = {
            'reset': reset,
        }
        send_mail_template(subject, template_name, context, [user.email])


class RegisterForm(forms.ModelForm):

    # não é mais necessário
    # email = forms.EmailField(label='E-mail')
    password1 = forms.CharField(label='Senha', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Confirmação de Senha', widget=forms.PasswordInput)

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                'A confirmação não está correta')
        return password2


#    def clean_email(self):
#        email = self.cleaned_data['email']
#        if User.objects.filter(email=email).exists():
#            raise forms.ValidationError('Já existe usuário com este E-mail.')
#
#        return email

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        # não precisa mais resgart o emal no form
        # user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['username', 'email']


class EditAccountForm(forms.ModelForm):

    # def clean_email(self):
    #     email = self.cleaned_data['email']
    #     queryset = User.objects.filter(
    #         email=email).exclude(pk=self.instance.pk)
    #     if queryset.exists():
    #         raise forms.ValidationError('Já existe usuário com este E-mail.')
    #
    #     return email

    class Meta:
        model = User
        fields = ['username', 'email', 'name']

simplemooc/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.forms import (
    PasswordChangeForm,
    SetPasswordForm)
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from simplemooc.core.utils import generate_hash_key
from simplemooc.courses.models import Enrollment

from .forms import RegisterForm, EditAccountForm, PasswordResetForm
from .models import PasswordReset

User = get_user_model()


@login_required
def dashboard(request):
    template_name = 'accounts/dashboard.html'
    context = {}
    # context['enrollments'] = Enrollment.objects.filter(user=request.user)
    return render(request, template_name, context)


def register(request):
    template_name = 'accounts/register.html'
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            user = authenticate(
                username=user.username,
                password=form.cleaned_data['password1']
            )
            login(request, user)
            return redirect('core:home')
    else:
        form = RegisterForm()

    context = {
        'form': form
    }
    return render(request, template_name, context)


def password_reset(request):
    template_name = 'accounts/password_reset.html'
    context = {}

    form = PasswordResetForm(request.POST or None)

    if form.is_valid():
        form.save()
        context['success'] = True

    context['form'] = form
    return render(request, template_name, context)


def password_reset_confirm(request, key):
    template_name = 'accounts/password_reset_confirm.html'
    context = {}
    reset = get_object_or_404(PasswordReset, key=key)
    form = SetPasswordForm(user=reset.user, data=request.POST or None)
    if form.is_valid():
        form.save()
        context['success'] = True
    context['form'] = form
    return render(request, template_name, context)


@login_required
def edit(request):
    template_name = 'accounts/edit.html'
    context = {}
    if request.method == 'POST':
        form = EditAccountForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            # form = EditAccountForm(instance=request.user)
            # context['sucess'] = True
            messages.success(
                request,
                'Os dados da sua conta foram alterados com sucess')
            return redirect('accounts:dashboard')

    else:
        form = EditAccountForm(instance=request.user)
    context['form'] = form
    return render(request, template_name, context)


@login_required
def edit_password(request):
    template_name = 'accounts/edit_password.html'
    context = {}
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            messages.success(request,'A sua senha foi alterada com sucesso')
            # context['sucess'] = True
            return redirect('accounts:dashboard')
    else:
        form = PasswordChangeForm(user=request.user)
    context['form'] = form
    return render(request, template_name, context)

simplemooc/accounts/templates/accounts/dashboard.html
{% extends "base.html" %}

{% load courses_tags %}

{% block content %}
{% load_my_courses user as enrollments %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <ul class="breadcrumb">
            {% block breadcrumps %}
            {{ block.super}}
            <li><a href="{% url 'accounts:dashboard' %}">Meu Painel</a></li>
            {% endblock %}
        </ul>
    </div>
    <div class="pure-u-1-3">
        <div class="pure-menu pure-menu-open">
            <ul>
                <li class="pure-menu-heading">Bem Vindo, {{ user }} </li>
                {% block menu_options %}
                <li class="pure-menu-heading">Cursos</li>
                {% for enrollment  in enrollments %}
                <li>
                    <a href="{% url 'courses:announcements' enrollment.course.slug %}">
                    <i class="fa fa-book" aria-hidden="true"></i>
                    {{ enrollment.course }}
                    </a>
                </li>
                {% empty %}
                <li>Nenhum curso encontrado</li>
                {% endfor %}
                <li class="pure-menu-heading">Conta</li>
                <li>
                    <a href="{% url 'accounts:edit' %}">
                    <i class="fa fa-info" aria-hidden="true"></i>
                    Editar Informações</a>
                    </li>
                <li>
                    <a href="{% url 'accounts:edit-password' %}">
                    <i class="fa fa-lock" aria-hidden="true"></i>
                    Editar Senha
                    </a>
                </li>
                {% endblock menu_options %}
            </ul>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="inner">
            {% block dashboard_content %}
                <h2>Meus Cursos</h2>
                {% for enrollment in enrollments %}
                <div class="well">
                    <h3>{{ enrollment.course }} 
                    ({{ enrollment.course.start_date|date:'d/m/Y'|default:'Sem data' }})</h3>
                    {{ enrollment.course.description|linebreaks}}
                    <div class="pure-controls">
                        <a href="{% url 'courses:announcements' enrollment.course.slug %}" class="pure-button pure-button-primary">Acessar</a>
                        <a href="{% url 'courses:undo_enrollment' enrollment.course.slug %}" class="pure-button button-error">Cancelar</a>
                    </div>
                </div>
                {% empty %}
                <aside class="pure-u-1">
                    <p>Nenhum curso inscrito</p>
                </aside>
                {% endfor %}

            {% endblock %}
        </div>
    </div>
</div>    
{% endblock %}

simplemooc/accounts/templates/accounts/edit.html
{% extends "accounts/dashboard.html" %}

{% block breadcrumbs %}
    {{ block.super }}
	<li>/</li>
	<li><a href="{% url 'accounts:edit' %}">Editar Conta</a></li>
{% endblock  %}

{% block dashboard_content %}
<form class="pure-form pure-form-stacked" method="POST">
	{% csrf_token %}
    <fieldset>
    	{{ form.non_field_errors }}
    	{% for field in form  %}
        <div class="pure-control-group">
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
        </div>
    	{% endfor %}
        <div class="pure-controls">
            <button type="submit" class="pure-button pure-button-primary">Enviar</button>
        </div>
    </fieldset>
</form>

{% endblock  %}

simplemooc/accounts/templates/accounts/edit_password.html
{% extends "accounts/dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'accounts:edit_password' %}">Editar Senha</a></li>
{% endblock %}

{% block dashboard_content %}
<form class="pure-form pure-form-stacked" method="post">
    {% csrf_token %}
    {% if success %}
    <p>A sua senha foi alterada com sucesso</p>
    {% endif %}
    <fieldset>
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="pure-control-group">
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        <div class="pure-controls">
            <button type="submit" class="pure-button pure-button-primary">Alterar Senha</button>
        </div>
    </fieldset>
</form>
{% endblock %}

simplemooc/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}

    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            <h2>Informe seus dados de cadastro</h2>
            <form class="pure-form pure-form-stacked" method="POST">
                {% csrf_token %}
                <fieldset>
                    {{ form.non_field_errors }}

                    {% for field in form %}
                    <div class="pure-control-group">
                        {{ field.label_tag }}
                        {{ field }}
                        {{ field.errors }}
                    </div>
                    {% endfor %}

                    <div class="pure-controls">
                        <button type="submit" class="pure-button pure-button-primary">Entrar</button>
                    </div>
                </fieldset>
                <p>
                    Não é cadastrado? <a href="{% url 'accounts:register' %}" title="">Cadastre-se</a> <br />
                    Esqueceusss a senha? <a href="{% url 'accounts:password_reset' %}" title="cadastrar">Nova senha</a> <br />
                </p>
            </form>
        </div>
    </div>
{% endblock %}

simplemooc/accounts/templates/accounts/password_reset.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
    	{% if success %}
    	<p>Um email foi enviado para você com mais detalhes de como criar uma nova senha</p>
    	{% else %}        	
        <h2>Informe seus email</h2>
        <form class="pure-form pure-form-stacked" method="POST">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                </div>
            </fieldset>
        </form>
    	{% endif %}
    </div>
</div>
{% endblock %}

simplemooc/accounts/templates/accounts/password_reset_confirm.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
    	{% if success %}
    	<p>Sua senha foi criada com sucesso</p>
    	{% else %}        	
        <h2>Informe sua nova senha</h2>
        <form class="pure-form pure-form-stacked" method="POST">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                </div>
            </fieldset>
        </form>
    	{% endif %}
    </div>
</div>
{% endblock %}

simplemooc/accounts/templates/accounts/password_reset_mail.html
<p>Para criar uma nova senha, acesso o link<a href="http://localhost:8000{% url 'accounts:password_reset_confirm' reset.key %}" title="Link para criar nova senha.">Criar nova senha</a></p>

simplemooc/accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}

    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            <h2>Informe seus dados de cadastro</h2>
            <form class="pure-form pure-form-stacked" method="POST">
                {% csrf_token %}
                <fieldset>
                    {{ form.non_field_errors }}

                    {% for field in form %}
                    <div class="pure-control-group">
                        {{ field.label_tag }}
                        {{ field }}
                        {{ field.errors }}
                    </div>
                    {% endfor %}

                    <div class="pure-controls">
                        <button type="submit" class="pure-button pure-button-primary">Cadastrar</button>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
{% endblock %}