simplemooc/core/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^contato/$', views.contact, name='contact'),
]

simplemooc/forum/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(
        r'^',
        views.index,
        name='index'
    ),
]

simplemooc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^', include('simplemooc.core.urls', namespace='core')),
    url(r'^conta/', include('simplemooc.accounts.urls', namespace='accounts')),
    url(r'^cursos/', include('simplemooc.courses.urls', namespace='courses')),
    url(r'^forum/', include('simplemooc.forum.urls', namespace='forum')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

simplemooc/forum/models.py
from django.db import models
from django.conf import settings
from taggit.managers import TaggableManager


class Thread(models.Model):
    title = models.CharField('Título', max_length=100)
    body = models.TextField('Menssagem')
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name='Autor',
        related_name='threads'
    )
    views = models.IntegerField('Visualizações', blank=True, default=0)
    answers = models.IntegerField('Respostas', blank=True, default=0)
    tags = TaggableManager()

    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Tópico'
        verbose_name_plural = 'Tópicos'
        ordering = ['-modified']


class Reply(models.Model):

    thread = models.ForeignKey(
        Thread,
        verbose_name='Tópico',
        related_name='replies'
    )
    retry = models.TextField('Resposta')
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name='Autor',
        related_name='replies'
    )
    correct = models.BooleanField('Correta?', blank=True, default=False)
    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    def __str__(self):
        self.reply[:100]

    class Meta:
        verbose_name = 'Respostas'
        verbose_name_plural = 'Respostas'
        ordering = ['-correct', 'created']

simplemooc/forum/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, View, ListView
from .models import Thread

# class ForumView(TemplateView):
#
#     template_name = 'forum/index.html'

#index = ForumView.as_view()
# index = TemplateView.as_view(
#      template_name='forum/index.html'
# )

class ForumView(ListView):

    model = Thread
    paginate_by = 10
    template_name = 'forum/index.html'

index = ForumView.as_view()

simplemooc/forum/templates/forum/index.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <ul class="breadcrumb">
            <li><a href="{% url 'core:home' %}">Início</a></li>
            <li>/</li>
            <li><a href="{% url 'forum:index' %}">Fórum de Discussões</a></li>
        </ul>
    </div>
    <div class="pure-u-1-3">
        <div class="pure-menu pure-menu-open">
            <ul>
                <li class="pure-menu-heading">
                    Tópicos do Fórum
                </li>
                <li>
                    <a href="?order=">
                        <i class="fa fa-refresh"></i>
                        Mais Recentes
                    </a>
                </li>
                <li>
                    <a href="?order=views">
                        <i class="fa fa-eye"></i>
                        Mais Visualizados
                    </a>
                </li>
                <li>
                    <a href="?order=answers">
                        <i class="fa fa-comments-o"></i>
                        Mais Comentados
                    </a>
                </li>
                <li class="pure-menu-heading">Tags</li>
                <li>
                    {% for tag in tags %}
                    <a href="#" class="tags">
                        <i class="fa fa-tag"></i>
                        {{ tag }}
                    </a>
                    {% endfor %}
                </li>
            </ul>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="inner">
            {% for thread in object_list %}
            <div class="well">
                <h3><a href="" title="">{{ thread.title }}</a></h3>
                <h5>
                    Criado por {{ thread.author }} | {{ thread.answers }} resposta{{ thread.answers|pluralize }} | {{ thread.views }} Visualizaç{{ thread.views|pluralize:"ão,ões" }} 
                </h5>
                <p>
                    <i class="fa fa-tags"></i>
                    Tags: 
                    {% for tag in thread.tags.all %}
                    <a href="" title="">{{ tag }}</a>{% if not forloop.last %},{% endif %}
                    {% endfor %}
                    <a class="fright" href="" title="">Atualizado a {{ thread.modified|timesince }} atrás</a>
                </p>
            </div>
            {% endfor %}
            <ul class="pagination pagination-centered">
                {% if page_obj.has_previous %}
                <li>
                    <a href="?page={{ page_obj.previous_page_number }}{% if request.GET.order %}&order={{ request.GET.order }}{% endif %}" title="">Anterior</a>
                </li>
                {% endif %}
                {% for page in paginator.page_range %}
                <li{% if page == page_obj.number %} class="active"{% endif %}>
                    <a href="?page={{ page }}{% if request.GET.order %}&order={{ request.GET.order }}{% endif %}" title="">{{ page }}</a>
                </li>
                {% endfor %}
                {% if page_obj.has_next %}
                <li>
                    <a href="?page={{ page_obj.next_page_number }}{% if request.GET.order %}&order={{ request.GET.order }}{% endif %}" title="">Próxima</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
	
{% endblock content %}